#!/bin/bash
# Author: Pablo Greco <pablo@fliagreco.com.ar>
# Based on java-1.6.0-openjdk test from Christoph Galuschka <christoph.galuschka@chello.at>

if [ ${centos_ver} -eq 10 ];then
JAVA_VERSIONS="21"
else
JAVA_VERSIONS="1.8.0 11 17"
fi
