#!/bin/bash
# Author: Iain Douglas <centos@1n6.org.uk>

t_Log "Running $0"

userdel -rf testshadow; useradd testshadow
echo "testshadow" | passwd --stdin testshadow

echo "Set last date passwd changed to 2013-01-01"
chage -d 2013-01-01 testshadow
t_CheckExitStatus $?

echo "Check that last passwd change is reported correctly"
check_date="Jan 01, 2013"
[ $centos_ver -eq 10 ] && check_date="Dec 31, 2012"
chage -l testshadow | grep Last | grep -q "${check_date}"
t_CheckExitStatus $?
